export const ADD_ANNOUNCEMENT = 'ADD_ANNOUNCEMENT';
export const EDIT_ANNOUNCEMENT = 'EDIT_ANNOUNCEMENT';
export const DELETE_ANNOUNCEMENT = 'DELETE_ANNOUNCEMENT';
export const SEARCH_ANNOUNCEMENT = 'SEARCH_ANNOUNCEMENT';
export const SIMILAR_ANNOUNCEMENT = 'SIMILAR_ANNOUNCEMENT';
export const RESET_ANNOUNCEMENT = 'RESET_ANNOUNCEMENT';